---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: polirelease
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helmchart
      sourceRef:
        kind: HelmRepository
        name: polihelm
  interval: 5m0s
  releaseName: polirelease
  targetNamespace: default

