---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmfluxrelease
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      sourceRef:
        kind: HelmRepository
        name: polihelm
  interval: 5m0s
  releaseName: helmfluxrelease
  targetNamespace: default

